language: d
sudo: false

install:
  - ./travis_install.sh

packages:
  - gcc-multilib

matrix:
  include:
    - d: dmd
    - d: ldc

script:
  - dub test --build=unittest-cov --compiler=${DC}
  - dub lint -- --styleCheck --skipTests

after_success:
  - bash <(curl -s https://codecov.io/bash)
